# Generated by Django 5.1 on 2024-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='No description provided', max_length=2000),
            preserve_default=False,
        ),
    ]
